# NUMPY


# how to create a numpy array:
    

In [8]:
import numpy as np

a=([[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]])

a=np.array(a, dtype = float)

print(a)


[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]


# numpy zeroes method:


In [9]:
b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



# reshaping the array:


In [32]:
array = np.arange(8)
print("Original array : \n", array)
 
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# shape array with 2 rows and 4 columns
array = np.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# Constructs 3D array
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# in the print statement:

In [11]:
print("A\n", np.arange(4).reshape(2, 2), "\n")
 
print("A\n", np.arange(4, 10), "\n")
 
print("A\n", np.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



# linspace:

In [34]:
print("B\n", np.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range 
x = np.linspace(0, 2, 10)
print("A\n", np.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


# flatten

In [14]:
array = np.array([[1, 2], [3, 4]])
 
# using flatten method
array.flatten()
print(array)
 
#using fatten method 
array.flatten('F')
print(array)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


# print largest element

In [16]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))
 
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
print ("Sum of all array elements:",
                            arr.sum())
 
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


# multiplying two lists

In [17]:
list1 = [1, 2, 3, 4, 5, 6]
list2 = [10, 9, 8, 7, 6, 5]

a1 = np.array(list1)

a2 = np.array(list2)
 
print(a1*a2)

[10 18 24 28 30 30]


# indexing 

In [18]:
# Create a sequence of integers from
# 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)
 
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [19]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
 
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# negative indexing

In [35]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
 
# Index values can be negative.
arr = x[np.array([1, 3, -3])]
print("\n Elements are : \n",arr)


 Elements are : 
 [2 4 7]


# Iterating Over Array



In [20]:
a = np.arange(12)
 
# shape array with 3 rows and 
# 4 columns
a = a.reshape(3,4)
 
print('Original array is:')
print(a)
print()
 
print('Modified array is:')
 
# iterating  an array
for x in np.nditer(a):
    print(x)

Original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Modified array is:
0
1
2
3
4
5
6
7
8
9
10
11


In [22]:
a = np.arange(0,60,5) 
 
# shape array with 3 rows and 
# 4 columns 
a = a.reshape(3,4) 
 
print('Original array is:') 
print(a)
print()  
 
print('Modified array in F-style order:')
 
# iterating an array in a given
# order   
for x in np.nditer(a, order = 'F'): 
    print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Modified array in F-style order:
0
20
40
5
25
45
10
30
50
15
35
55


In [23]:
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 5*x
print('Modified array is:')
print(a)

Modified array is:
[[  0  25  50  75]
 [100 125 150 175]
 [200 225 250 275]]


# mathematical functions:
    

In [24]:
import numpy as np
import math
 
in_array = [0, math.pi / 2, np.pi / 3, np.pi]
print ("Input array : \n", in_array)
 
cos_Values = np.cos(in_array)
print ("\nCosine values : \n", cos_Values)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

Cosine values : 
 [ 1.000000e+00  6.123234e-17  5.000000e-01 -1.000000e+00]


# string operations

In [25]:
print(np.char.lower(['SWATI', 'SRIVASTAVA']))
 


['swati' 'srivastava']


In [26]:
print(np.char.split('swati srivastava 0211'))

['swati', 'srivastava', '0211']


In [27]:
print(np.char.join(['-', ':'], ['Swati', 'Srivastava'])) #joining

['S-w-a-t-i' 'S:r:i:v:a:s:t:a:v:a']


In [28]:
# linear algebraic functions :
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [29]:
# sorting

a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 0)        
print ("Along first axis : \n", arr1)        
 
 
# sort along the last axis
a = np.array([[10, 15], [12, 1]])
arr2 = np.sort(a, axis = -1)        
print ("\nAlong first axis : \n", arr2)
 
 
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [30]:
a = np.array([9, 3, 1, 7, 4, 3, 6])
 
# unsorted array print
print('Original array:\n', a)
 
# Sort array indices
b = np.argsort(a)
print('Sorted indices of original array->', b)
 
# To get sorted array using sorted indices
# c is temp array created of same len as of b
c = np.zeros(len(b), dtype = int)
for i in range(0, len(b)):
    c[i]= a[b[i]]
print('Sorted array->', c)

Original array:
 [9 3 1 7 4 3 6]
Sorted indices of original array-> [2 1 5 4 6 3 0]
Sorted array-> [1 3 3 4 6 7 9]


# searching

In [31]:
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmax(array))
 
# returning Indices of the max element
# as per the indices
print(("\nIndices of Max element : "
      , np.argmax(array, axis=0)))
print(("\nIndices of Max element : "
      , np.argmax(array, axis=1)))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11
('\nIndices of Max element : ', array([2, 2, 2, 2]))
('\nIndices of Max element : ', array([3, 3, 3]))
